export type Landmark = {
  key: string; role: "hero" | "index"; label: string; place: string;
  src: string; width: number; height: number; objectPosition: string;
  alt: string; caption: string; credit: string; source: string;
  license: string; licenseUrl: string; modification: string;
};

export const landmarks: Landmark[] = [
  { key: "borobudur", role: "hero", label: "Borobudur Stupa with Mount Merapi", place: "Borobudur, Indonesia", src: "/borobudur-stupa-merapi.webp", width: 1536, height: 1024, objectPosition: "center", alt: "Bell-shaped stupas at Borobudur with Mount Merapi visible in the distance.", caption: "Borobudur, Central Java", credit: "Photo by ctsnow", source: "https://commons.wikimedia.org/wiki/File:Borobudur_Stupa_Merapi.jpg", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", modification: "Cropped and resized for KelanaAI." },
  { key: "eiffel", role: "index", label: "Eiffel Tower, Paris", place: "Paris, France", src: "/landmarks/eiffel-tower-paris.webp", width: 1600, height: 1200, objectPosition: "center", alt: "Eiffel Tower viewed from the Champ de Mars in Paris.", caption: "Eiffel Tower, Paris", credit: "Photo by trolvag", source: "https://commons.wikimedia.org/wiki/File:Eiffel_tower,_Champ_de_Mars,_Paris,_France_-_panoramio.jpg", license: "CC BY-SA 3.0 Unported", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
  { key: "nijo", role: "index", label: "Ninomaru Palace, Nijō Castle, Kyoto", place: "Kyoto, Japan", src: "/landmarks/nijo-castle-ninomaru.webp", width: 1280, height: 960, objectPosition: "center", alt: "Entrance facade of Ninomaru Palace at Nijō Castle in Kyoto.", caption: "Ninomaru Palace, Kyoto", credit: "Photo by CCP2017", source: "https://commons.wikimedia.org/wiki/File:Nijo_Castle_2017.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
  { key: "golden-gate", role: "index", label: "Golden Gate Bridge from Battery Spencer", place: "Marin Headlands, United States", src: "/landmarks/golden-gate-bridge-battery-spencer.webp", width: 1280, height: 853, objectPosition: "center", alt: "Golden Gate Bridge in fog and evening sun, viewed from Battery Spencer in California.", caption: "Golden Gate Bridge, California", credit: "Photo by Radomianin", source: "https://commons.wikimedia.org/wiki/File:Golden_Gate_Bridge,_North_view.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
  { key: "red-square", role: "index", label: "Kremlin and Red Square, Moscow", place: "Moscow, Russia", src: "/landmarks/kremlin-red-square-moscow.webp", width: 1280, height: 850, objectPosition: "center", alt: "Aerial view of the Moscow Kremlin beside Red Square.", caption: "Kremlin and Red Square, Moscow", credit: "Source: Mos.ru / Government of Moscow Press centre", source: "https://commons.wikimedia.org/wiki/File:Kremlin_and_Red_Square.1.jpg", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", modification: "Cropped, resized, and recompressed." },
  { key: "machu-picchu", role: "index", label: "Machu Picchu citadel, Peru", place: "Cusco Region, Peru", src: "/landmarks/machu-picchu-citadel.webp", width: 1280, height: 851, objectPosition: "center", alt: "Ancient stone houses of Machu Picchu on a mountain ridge in Peru.", caption: "Machu Picchu, Peru", credit: "Photo by Diego Delso (Commons account: Poco a poco)", source: "https://commons.wikimedia.org/wiki/File:Machu_Picchu,_Per%C3%BA,_2015-07-30,_DD_47.JPG", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
  { key: "petra", role: "index", label: "View toward Al-Khazneh at Petra, Jordan", place: "Wadi Musa, Jordan", src: "/landmarks/petra-al-khazneh.webp", width: 1600, height: 1067, objectPosition: "center", alt: "View toward Al-Khazneh at Petra, Jordan, from Jabal al-Khubtha.", caption: "Al-Khazneh at Petra, Jordan", credit: "Photo by Hashem sabbagh", source: "https://commons.wikimedia.org/wiki/File:Petra_From_Above.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
  { key: "sydney", role: "index", label: "Sydney Opera House at dawn", place: "Sydney, Australia", src: "/landmarks/sydney-opera-house-dawn.webp", width: 960, height: 640, objectPosition: "center", alt: "Sydney Opera House in early morning light, with city buildings behind it.", caption: "Sydney Opera House, Australia", credit: "Photo by Alan Kenneth Dicker / Albyontour", source: "https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_at_Dawn.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", modification: "Cropped, resized, and recompressed; share-alike terms retained." },
];

export const heroLandmark = landmarks[0];
export const indexLandmarks = landmarks.slice(1);