[project]
name = "kelanaai"
version = "0.1.0"
requires-python = ">=3.12,<3.14"
dependencies = [
    "fastapi[standard]==0.141.1",
    "uvicorn[standard]==0.52.3",
    "httpx==0.28.1",
    "SQLAlchemy==2.0.52",
    "psycopg[binary]==3.3.4",
    "python-dotenv==1.2.3",
    "boto3==1.43.4",
    "argon2-cffi==25.1.0",
]

[tool.fastapi]
entrypoint = "backend.main:app"
